# Generated by Django 5.0.6 on 2024-06-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_studentassignment_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_text', models.TextField()),
                ('notif_for', models.CharField(max_length=200)),
                ('notif_created_time', models.DateTimeField(auto_now_add=True)),
                ('notif_read_status', models.BooleanField(default=False)),
            ],
        ),
    ]
