# Generated by Django 5.0.6 on 2024-06-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_notification_notif_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notif_read_status',
            new_name='notifiread_status',
        ),
    ]
